# 作用于 NET 核 hci_ipc 子镜像（不要写 CONFIG_BT_HCI_RAW）
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2

# 仅做增量控制器参数
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_CTLR_ASSERT_HANDLER=y
