# STEP 2.3 - Enable logging for MCUboot
CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y
# use mbedTLS and ECDSA-P256(small volumn)
CONFIG_BOOT_USE_MBEDTLS=y
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
# private key path(under main path)
CONFIG_BOOT_SIGNATURE_KEY_FILE="signing-priv.pem"
# when fail, it will recover automatically
CONFIG_MCUBOOT_SWAP_USING_SCRATCH=y
CONFIG_MCUBOOT_VALIDATE_PRIMARY_SLOT=y
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=y

# Step 1.2 - Enable SPI driver for MCUboot
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_DEVICETREE=y
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
# QSPI drivers are enabled by defualt for some chips.
# Disable it explicitly to be sure QSPI is disabled.
CONFIG_NORDIC_QSPI_NOR=n 

# required by SPI driver
CONFIG_MULTITHREADING=y

# STEP 4.1 - Increase number of sectors
# This is 512 for the nRF54L15 but can be smaller for other chips
CONFIG_BOOT_MAX_IMG_SECTORS=512

