CONFIG_GPIO=y

#Sensor Framework + I2C
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

###### Bluetooth
#Bluetooth Setup
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="ESE5180-BME"

# Save pairing information
CONFIG_SETTINGS=y
CONFIG_BT_SETTINGS=y

#UART
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

#Print(float)
CONFIG_CBPRINTF_COMPLETE=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

#LOG Information
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y

CONFIG_LOG_MODE_DEFERRED=y

