CONFIG_GPIO=y

#Sensor Framework + I2C
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

#BME280 Driver
# CONFIG_BME280=y

#UART
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

#Print(float)
CONFIG_CBPRINTF_COMPLETE=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

#LOG Information
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y

CONFIG_LOG_MODE_DEFERRED=y
