# Enable network core with HCI IPC for nRF5340
SB_CONFIG_NETCORE_HCI_IPC=y

# #double slot
# SB_CONFIG_MCUBOOT_MODE_SINGLE_APP=n
# #bootloader
# SB_CONFIG_BOOTLOADER_MCUBOOT=y
# # STEP 2.1 - Add private key for MCUboot
# SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APP_DIR}/signing-priv.pem"
# # STEP 2.2. - Configure key type
# SB_CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y

# # STEP 3.1 - MCUboot should use external flash
# SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
# # STEP 3.1 - For SPI, we need to set this
# # SB_CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y